name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: MacOS
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode 12.4
      run: sudo xcode-select -s /Applications/Xcode_12.4.app
    - name: Run tests
      run: make test-swift
      env:
          SNAPSHOT_ARTIFACTS: "./.temp/artifacts"

    - name: Archive failing snapshots
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: failing-snapshots
        path: .temp/artifacts/MacSnapshottestingTests/*.png


  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: make test-linux
